#!/usr/bin/env python3
"""Generate esp32-body/src/faces_table.h from neatobmo/faces.py.

neatobmo/faces.py is the single source of truth for the face vocabulary
(grid geometry + emoji map).  The firmware includes the generated header,
so a face change is one Python edit + one regeneration — the old
"change faces.py *and* faces.c" prose contract is now a build artifact.
tests/test_emote.py asserts the committed header matches this output.

    python3 tools/gen_faces_table.py            # rewrite the header
    python3 tools/gen_faces_table.py --check    # exit 1 if out of date
"""
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from neatobmo import faces

HEADER = ROOT / "esp32-body" / "src" / "faces_table.h"

# neatobmo/faces.py insertion order defines the enum order
FACE_ORDER = list(faces.FACES)


def c_face(name):
    return "F_" + name.upper()


def c_utf8(emoji):
    return '"' + "".join(f"\\x{b:02X}" for b in emoji.encode()) + '"'


def generate():
    lines = [
        "/* GENERATED by tools/gen_faces_table.py from neatobmo/faces.py —",
        " * do not edit; edit faces.py and regenerate.  The Python module is",
        " * the single source of truth for face geometry and the emoji map. */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"#define FACES_MAX_CASCADE {faces.MAX_CASCADE}",
        "",
        "typedef enum {",
        "    " + ", ".join(c_face(n) for n in FACE_ORDER) + ",",
        "    FACE_COUNT,",
        "} face_t;",
        "",
        "/* Column spans for the two eye pillars + up to two row bands for the",
        " * mouth ([lo,hi] inclusive; second band unused when b2hi == 0). */",
        "typedef struct {",
        "    uint8_t l0, l1, r0, r1;     /* left / right pillar columns */",
        "    uint8_t b1lo, b1hi;         /* mouth band 1 rows */",
        "    uint8_t b2lo, b2hi;         /* mouth band 2 rows (0,0 = none) */",
        "} geo_t;",
        "",
        "static const geo_t GEO[] = {",
    ]
    width = max(len(c_face(n)) for n in FACE_ORDER)
    for name in FACE_ORDER:
        cols, rows = faces.FACES[name]
        assert len(cols) == 2, f"{name}: firmware geometry needs 2 pillars"
        assert 1 <= len(rows) <= 2, f"{name}: firmware supports 1-2 bands"
        (l0, l1), (r0, r1) = cols
        (b1lo, b1hi) = rows[0]
        (b2lo, b2hi) = rows[1] if len(rows) > 1 else (0, 0)
        lines.append(f"    [{c_face(name):<{width}}] = "
                     f"{{ {l0}, {l1}, {r0}, {r1}, "
                     f"{b1lo}, {b1hi}, {b2lo}, {b2hi} }},")
    lines += [
        "};",
        "",
        "typedef struct { const char *utf8; face_t face; } emap_t;",
        "",
        "static const emap_t EMAP[] = {",
    ]
    for emoji, name in faces.EMOJI_FACES.items():
        lines.append(f"    {{ {c_utf8(emoji)}, {c_face(name)} }},  "
                     f"/* {emoji} */")
    lines += ["};", ""]
    return "\n".join(lines)


if __name__ == "__main__":
    content = generate()
    if "--check" in sys.argv:
        if not HEADER.exists() or HEADER.read_text() != content:
            print(f"{HEADER} is out of date — run tools/gen_faces_table.py")
            sys.exit(1)
        print("faces_table.h is in sync")
    else:
        HEADER.write_text(content)
        print(f"wrote {HEADER}")
