/* GENERATED by tools/gen_faces_table.py from neatobmo/faces.py —
 * do not edit; edit faces.py and regenerate.  The Python module is
 * the single source of truth for face geometry and the emoji map. */
#pragma once
#include <stdint.h>

#define FACES_MAX_CASCADE 8

typedef enum {
    F_NEUTRAL, F_HAPPY, F_LAUGH, F_LOVE, F_SAD, F_SURPRISED, F_WINK, F_SLEEPY, F_ANGRY, F_PARTY, F_BLINK,
    FACE_COUNT,
} face_t;

/* Column spans for the two eye pillars + up to two row bands for the
 * mouth ([lo,hi] inclusive; second band unused when b2hi == 0). */
typedef struct {
    uint8_t l0, l1, r0, r1;     /* left / right pillar columns */
    uint8_t b1lo, b1hi;         /* mouth band 1 rows */
    uint8_t b2lo, b2hi;         /* mouth band 2 rows (0,0 = none) */
} geo_t;

static const geo_t GEO[] = {
    [F_NEUTRAL  ] = { 34, 42, 86, 94, 44, 46, 0, 0 },
    [F_HAPPY    ] = { 34, 42, 86, 94, 42, 50, 0, 0 },
    [F_LAUGH    ] = { 32, 44, 84, 96, 40, 52, 0, 0 },
    [F_LOVE     ] = { 32, 44, 84, 96, 42, 50, 0, 0 },
    [F_SAD      ] = { 34, 42, 86, 94, 52, 54, 0, 0 },
    [F_SURPRISED] = { 30, 46, 82, 98, 36, 55, 0, 0 },
    [F_WINK     ] = { 32, 44, 89, 91, 42, 50, 0, 0 },
    [F_SLEEPY   ] = { 37, 39, 89, 91, 48, 50, 0, 0 },
    [F_ANGRY    ] = { 32, 44, 84, 96, 48, 50, 54, 56 },
    [F_PARTY    ] = { 30, 46, 82, 98, 40, 42, 46, 52 },
    [F_BLINK    ] = { 37, 39, 89, 91, 44, 46, 0, 0 },
};

typedef struct { const char *utf8; face_t face; } emap_t;

static const emap_t EMAP[] = {
    { "\xF0\x9F\x98\x80", F_HAPPY },  /* 😀 */
    { "\xF0\x9F\x98\x84", F_HAPPY },  /* 😄 */
    { "\xF0\x9F\x98\x8A", F_HAPPY },  /* 😊 */
    { "\xF0\x9F\x99\x82", F_HAPPY },  /* 🙂 */
    { "\xF0\x9F\x98\x82", F_LAUGH },  /* 😂 */
    { "\xF0\x9F\xA4\xA3", F_LAUGH },  /* 🤣 */
    { "\xF0\x9F\x98\x8D", F_LOVE },  /* 😍 */
    { "\xE2\x9D\xA4", F_LOVE },  /* ❤ */
    { "\xF0\x9F\x92\x96", F_LOVE },  /* 💖 */
    { "\xF0\x9F\x92\x9A", F_LOVE },  /* 💚 */
    { "\xF0\x9F\x98\xA2", F_SAD },  /* 😢 */
    { "\xF0\x9F\x98\xAD", F_SAD },  /* 😭 */
    { "\xF0\x9F\x98\x9E", F_SAD },  /* 😞 */
    { "\xE2\x98\xB9", F_SAD },  /* ☹ */
    { "\xF0\x9F\x98\xAE", F_SURPRISED },  /* 😮 */
    { "\xF0\x9F\x98\xB2", F_SURPRISED },  /* 😲 */
    { "\xF0\x9F\x98\xB1", F_SURPRISED },  /* 😱 */
    { "\xF0\x9F\x98\x89", F_WINK },  /* 😉 */
    { "\xF0\x9F\x98\xB4", F_SLEEPY },  /* 😴 */
    { "\xF0\x9F\x92\xA4", F_SLEEPY },  /* 💤 */
    { "\xF0\x9F\x98\xA0", F_ANGRY },  /* 😠 */
    { "\xF0\x9F\x98\xA4", F_ANGRY },  /* 😤 */
    { "\xF0\x9F\x8E\x89", F_PARTY },  /* 🎉 */
    { "\xF0\x9F\x8E\xAE", F_PARTY },  /* 🎮 */
    { "\xE2\x9C\xA8", F_PARTY },  /* ✨ */
    { "\xF0\x9F\xA4\x96", F_NEUTRAL },  /* 🤖 */
};
